---
framework: jest
blocklist:
  - "test/algorithms/geometric-test.js##geometric algorithm##should have inverse functions for getValue and getPosition"
postMerge:
  pattern:
    - "test/algorithms/geometric-test.js"
preMerge:
  pattern:
    - "test/algorithms/geometric-test.js"

preRun:
  command:
    - npm i
    - npm run react
postRun:
  command:
    - node --version
version: 1.2.1

